name: Deploy Number Guessing Game-Temporary Fix

on:
  workflow_dispatch:     
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm i
      working-directory: ./number-guessing-game

    - name: Create dummy properties
      run: | 
       echo "APP_DEV_PK=73315877021c8545736bc16beafd9b42307f2b7009a80cb0d1e412f1a46754d4" > .env
       echo "END_USR_PK=6dd788b1f967133d89f5815e7aff70c97be3f13f6e6ae51fa12af7c5df0fe09e" >> .env
       echo "ARB_API_KEY=djdjbfsdbksdjfksdbfksdbfsk" >> .env 
      working-directory: ./number-guessing-game

    - name: Compile contract
      run: npx hardhat clean & npx hardhat compile 
      working-directory: ./number-guessing-game

    - name: Build application
      run: npm run build --if-present
      working-directory: ./number-guessing-game
  
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./number-guessing-game/dist
        destination_dir: ./number-guessing-game
