# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Number Guessing Game front end

on:
  workflow_dispatch:     
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm i
      working-directory: ./number-guessing-game

    - name: Install Hardhat with ESM support
      run: npm i hardhat@esm
      working-directory: ./number-guessing-game

    - name: Compile contract
      run: npx hardhat clean & npx hardhat compile 
      working-directory: ./number-guessing-game

    - name: Build application
      run: npm run build --if-present
      working-directory: ./number-guessing-game
  
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./number-guessing-game/dist
        destination_dir: ./number-guessing-game
